#! /usr/bin/python3

import os
import sys
import DataDating.View

httpd = DataDating.View.Server()

try:
    httpd.serve_forever()

except DataDating.View.Termination:
    httpd.shutdown()
    print("Bye! :)")

except KeyboardInterrupt:
    httpd.shutdown()
    print("\nBye! :)")

    

